#!/bin/bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
osname="$(uname)"
case $osname in
    Darwin | darwin)
        osname=darwin
        ;;
    Linux | linux | GNU/Linux)
        osname=linux
        ;;
    *)
        echo "Unsupported OS: $osname"
        exit 1
        ;;
esac
arch="$(uname -m)"
case $arch in
    x86_64)
        arch=amd64
        ;;
    armv8l | aarch64)
        arch=arm64
        ;;
    *)
        echo "Unsupported architecture: $arch"
        exit 1
        ;;
esac

binary_name="buildpackify-${osname}-${arch}"

if [ -e "${script_dir}/${binary_name}" ]; then
    "${script_dir}/${binary_name}" generate "$@"
    exit $?
fi

if [ -e "${script_dir}/dist/${binary_name}" ]; then
    "${script_dir}/dist/${binary_name}" generate "$@"
    exit $?
fi

echo "Unable to find buildpackify binary for ${osname} ${arch}!"